version: '3.7'

services:
  server:
    build: ./
    container_name: CloudService
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/postgres
      spring.jpa.hibernate.ddl-auto: create-drop
    ports:
      - "8099:8099"
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"